// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: interop.triple_wrapper.proto

// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package interoperability

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripleRequestWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hessian4
	// json
	SerializeType string   `protobuf:"bytes,1,opt,name=serializeType,proto3" json:"serializeType,omitempty"`
	Args          [][]byte `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	ArgTypes      []string `protobuf:"bytes,3,rep,name=argTypes,proto3" json:"argTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripleRequestWrapper) Reset() {
	*x = TripleRequestWrapper{}
	mi := &file_interop_triple_wrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripleRequestWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripleRequestWrapper) ProtoMessage() {}

func (x *TripleRequestWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_interop_triple_wrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripleRequestWrapper.ProtoReflect.Descriptor instead.
func (*TripleRequestWrapper) Descriptor() ([]byte, []int) {
	return file_interop_triple_wrapper_proto_rawDescGZIP(), []int{0}
}

func (x *TripleRequestWrapper) GetSerializeType() string {
	if x != nil {
		return x.SerializeType
	}
	return ""
}

func (x *TripleRequestWrapper) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *TripleRequestWrapper) GetArgTypes() []string {
	if x != nil {
		return x.ArgTypes
	}
	return nil
}

type TripleResponseWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerializeType string                 `protobuf:"bytes,1,opt,name=serializeType,proto3" json:"serializeType,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripleResponseWrapper) Reset() {
	*x = TripleResponseWrapper{}
	mi := &file_interop_triple_wrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripleResponseWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripleResponseWrapper) ProtoMessage() {}

func (x *TripleResponseWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_interop_triple_wrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripleResponseWrapper.ProtoReflect.Descriptor instead.
func (*TripleResponseWrapper) Descriptor() ([]byte, []int) {
	return file_interop_triple_wrapper_proto_rawDescGZIP(), []int{1}
}

func (x *TripleResponseWrapper) GetSerializeType() string {
	if x != nil {
		return x.SerializeType
	}
	return ""
}

func (x *TripleResponseWrapper) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TripleResponseWrapper) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_interop_triple_wrapper_proto protoreflect.FileDescriptor

const file_interop_triple_wrapper_proto_rawDesc = "" +
	"\n" +
	"\x1cinterop.triple_wrapper.proto\x12\x10interoperability\"l\n" +
	"\x14TripleRequestWrapper\x12$\n" +
	"\rserializeType\x18\x01 \x01(\tR\rserializeType\x12\x12\n" +
	"\x04args\x18\x02 \x03(\fR\x04args\x12\x1a\n" +
	"\bargTypes\x18\x03 \x03(\tR\bargTypes\"e\n" +
	"\x15TripleResponseWrapper\x12$\n" +
	"\rserializeType\x18\x01 \x01(\tR\rserializeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04typeBiZgdubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol/internal/interoperability;interoperabilityb\x06proto3"

var (
	file_interop_triple_wrapper_proto_rawDescOnce sync.Once
	file_interop_triple_wrapper_proto_rawDescData []byte
)

func file_interop_triple_wrapper_proto_rawDescGZIP() []byte {
	file_interop_triple_wrapper_proto_rawDescOnce.Do(func() {
		file_interop_triple_wrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interop_triple_wrapper_proto_rawDesc), len(file_interop_triple_wrapper_proto_rawDesc)))
	})
	return file_interop_triple_wrapper_proto_rawDescData
}

var file_interop_triple_wrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interop_triple_wrapper_proto_goTypes = []any{
	(*TripleRequestWrapper)(nil),  // 0: interoperability.TripleRequestWrapper
	(*TripleResponseWrapper)(nil), // 1: interoperability.TripleResponseWrapper
}
var file_interop_triple_wrapper_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interop_triple_wrapper_proto_init() }
func file_interop_triple_wrapper_proto_init() {
	if File_interop_triple_wrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interop_triple_wrapper_proto_rawDesc), len(file_interop_triple_wrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interop_triple_wrapper_proto_goTypes,
		DependencyIndexes: file_interop_triple_wrapper_proto_depIdxs,
		MessageInfos:      file_interop_triple_wrapper_proto_msgTypes,
	}.Build()
	File_interop_triple_wrapper_proto = out.File
	file_interop_triple_wrapper_proto_goTypes = nil
	file_interop_triple_wrapper_proto_depIdxs = nil
}
