/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

import (
	registry "dubbo.apache.org/dubbo-go/v3/registry"
)

// NotifyListener is an autogenerated mock type for the NotifyListener type
type NotifyListener struct {
	mock.Mock
}

// Notify provides a mock function with given fields: _a0
func (_m *NotifyListener) Notify(_a0 *registry.ServiceEvent) {
	_m.Called(_a0)
}

// NotifyAll provides a mock function with given fields: _a0, _a1
func (_m *NotifyListener) NotifyAll(_a0 []*registry.ServiceEvent, _a1 func()) {
	_m.Called(_a0, _a1)
}
