//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: samples/adaptive_service/protect_provider/proto/protect.proto

package protectpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PayloadBytes  int32                  `protobuf:"varint,2,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_samples_adaptive_service_protect_provider_proto_protect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_adaptive_service_protect_provider_proto_protect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkRequest) GetPayloadBytes() int32 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_samples_adaptive_service_protect_provider_proto_protect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_adaptive_service_protect_provider_proto_protect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_samples_adaptive_service_protect_provider_proto_protect_proto protoreflect.FileDescriptor

const file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDesc = "" +
	"\n" +
	"=samples/adaptive_service/protect_provider/proto/protect.proto\x12\x10adaptive.protect\"F\n" +
	"\vWorkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rpayload_bytes\x18\x02 \x01(\x05R\fpayloadBytes\"D\n" +
	"\fWorkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence2Y\n" +
	"\x0eProtectService\x12G\n" +
	"\x04Work\x12\x1d.adaptive.protect.WorkRequest\x1a\x1e.adaptive.protect.WorkResponse\"\x00BXZVdubbo.apache.org/dubbo-go/v3/samples/adaptive_service/protect_provider/proto;protectpbb\x06proto3"

var (
	file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescOnce sync.Once
	file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescData []byte
)

func file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescGZIP() []byte {
	file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescOnce.Do(func() {
		file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDesc), len(file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDesc)))
	})
	return file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDescData
}

var file_samples_adaptive_service_protect_provider_proto_protect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_samples_adaptive_service_protect_provider_proto_protect_proto_goTypes = []any{
	(*WorkRequest)(nil),  // 0: adaptive.protect.WorkRequest
	(*WorkResponse)(nil), // 1: adaptive.protect.WorkResponse
}
var file_samples_adaptive_service_protect_provider_proto_protect_proto_depIdxs = []int32{
	0, // 0: adaptive.protect.ProtectService.Work:input_type -> adaptive.protect.WorkRequest
	1, // 1: adaptive.protect.ProtectService.Work:output_type -> adaptive.protect.WorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_samples_adaptive_service_protect_provider_proto_protect_proto_init() }
func file_samples_adaptive_service_protect_provider_proto_protect_proto_init() {
	if File_samples_adaptive_service_protect_provider_proto_protect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDesc), len(file_samples_adaptive_service_protect_provider_proto_protect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_samples_adaptive_service_protect_provider_proto_protect_proto_goTypes,
		DependencyIndexes: file_samples_adaptive_service_protect_provider_proto_protect_proto_depIdxs,
		MessageInfos:      file_samples_adaptive_service_protect_provider_proto_protect_proto_msgTypes,
	}.Build()
	File_samples_adaptive_service_protect_provider_proto_protect_proto = out.File
	file_samples_adaptive_service_protect_provider_proto_protect_proto_goTypes = nil
	file_samples_adaptive_service_protect_provider_proto_protect_proto_depIdxs = nil
}
