version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log, logrus is allowed to use only in logutils package
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 10
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - nto
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: '(SA1019|ST1001):'
    paths:
      - test/testdata_etc
      - pkg/golinters/goanalysis/(checker|passes)
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
