
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dubboclient
    service: dubboclient
  name: dubboclient
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: dubboclient
  type: ClusterIP

---

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  name: dubboclient

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubboclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubboclient
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        istio.io/rev: default
      labels:
        app: dubboclient
        version: v1
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/2456868764/dubbo-client:1.3.1
          imagePullPolicy: IfNotPresent
          name: dubboclient
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DUBBO_SERVER_URL
              value: httpbin.dubbo.svc:8000
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: CLUSTER_DOMAIN
              value: cluster.local
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: dubboclient
      serviceAccountName: dubboclient
      terminationGracePeriodSeconds: 30
---