  # dubbo client yaml configure file

filter: ""

# client
request_timeout : "100ms"
# connect timeout
connect_timeout : "100ms"
check: true
# application config
application_config:
  organization : "ikurento.com"
  name  : "BDTService"
  module : "dubbogo user-info client"
  version : "0.0.1"
  owner : "ZX"
  environment : "dev"

registries :
  "hangzhouzk":
    protocol: "zookeeper"
    timeout	: "3s"
    address: "127.0.0.1:2181"
    username: ""
    password: ""


references:
  "UserProvider":
    registry: "hangzhouzk"
    filter: "hystrix"
    protocol : "dubbo"
    interface : "com.ikurento.user.UserProvider"
    cluster: "failover"
    methods :
      - name: "GetUser"
        retries: 3

protocol_conf:
  dubbo:
    reconnect_interval: 0
    connection_number: 2
    heartbeat_period: "5s"
    session_timeout: "20s"
    fail_fast_timeout: "5s"
    pool_size: 64
    pool_ttl: 600
    getty_session_param:
      compress_encoding: false
      tcp_no_delay: true
      tcp_keep_alive: true
      keep_alive_period: "120s"
      tcp_r_buf_size: 262144
      tcp_w_buf_size: 65536
      pkg_rq_size: 1024
      pkg_wq_size: 512
      tcp_read_timeout: "1s"
      tcp_write_timeout: "5s"
      wait_timeout: "1s"
      max_msg_len: 1024
      session_name: "client"

filter_conf:
  hystrix:
    configs:
      "Default":
        timeout : 1000
        max_concurrent_requests : 10
        sleep_window : 5000
        error_percent_threshold : 50
        request_volume_threshold: 20
      "userp":
        timeout: 800
        max_concurrent_requests: 8
        sleep_window: 4
        error_percent_threshold: 45
        request_volume_threshold: 15
      "userp_m":
        timeout : 1200
        max_concurrent_requests : 12
        sleep_window : 6000
        error_percent_threshold : 60
        request_volume_threshold: 30
        fallback: "exampleFallback"
    default: "Default"
    services:
      "com.ikurento.user.UserProvider":
        service_config: "userp"
        methods:
          "GetUser": "userp_m"