/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: protocol\triple\health\triple_health\health.proto
package triple_health

import (
	"context"
	"net/http"
)

import (
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "health.HealthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HealthServiceCheckProcedure is the fully-qualified name of the HealthService's Check RPC.
	HealthServiceCheckProcedure = "/health.HealthService/Check"
	// HealthServiceWatchProcedure is the fully-qualified name of the HealthService's Watch RPC.
	HealthServiceWatchProcedure = "/health.HealthService/Watch"
)

var (
	_ HealthService = (*HealthServiceImpl)(nil)

	_ HealthService_WatchClient = (*HealthServiceWatchClient)(nil)

	_ HealthService_WatchServer = (*HealthServiceWatchServer)(nil)
)

// HealthService is a client for the health.HealthService service.
type HealthService interface {
	Check(ctx context.Context, req *HealthCheckRequest, opts ...client.CallOption) (*HealthCheckResponse, error)
	Watch(ctx context.Context, req *HealthCheckRequest, opts ...client.CallOption) (HealthService_WatchClient, error)
}

// NewHealthService constructs a client for the health.HealthService service.
func NewHealthService(cli *client.Client) (HealthService, error) {
	if err := cli.Init(&HealthService_ClientInfo); err != nil {
		return nil, err
	}
	return &HealthServiceImpl{
		cli: cli,
	}, nil
}

// HealthServiceImpl implements HealthService.
type HealthServiceImpl struct {
	cli *client.Client
}

func (c *HealthServiceImpl) Check(ctx context.Context, req *HealthCheckRequest, opts ...client.CallOption) (*HealthCheckResponse, error) {
	resp := new(HealthCheckResponse)
	if err := c.cli.CallUnary(ctx, req, resp, "health.HealthService", "Check", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *HealthServiceImpl) Watch(ctx context.Context, req *HealthCheckRequest, opts ...client.CallOption) (HealthService_WatchClient, error) {
	stream, err := c.cli.CallServerStream(ctx, req, "health.HealthService", "Watch", opts...)
	if err != nil {
		return nil, err
	}
	rawStream := stream.(*triple_protocol.ServerStreamForClient)
	return &HealthServiceWatchClient{rawStream}, nil
}

type HealthService_WatchClient interface {
	Recv() bool
	ResponseHeader() http.Header
	ResponseTrailer() http.Header
	Msg() *HealthCheckResponse
	Err() error
	Conn() (triple_protocol.StreamingClientConn, error)
	Close() error
}

type HealthServiceWatchClient struct {
	*triple_protocol.ServerStreamForClient
}

func (cli *HealthServiceWatchClient) Recv() bool {
	msg := new(HealthCheckResponse)
	return cli.ServerStreamForClient.Receive(msg)
}

func (cli *HealthServiceWatchClient) Msg() *HealthCheckResponse {
	msg := cli.ServerStreamForClient.Msg()
	if msg == nil {
		return new(HealthCheckResponse)
	}
	return msg.(*HealthCheckResponse)
}

func (cli *HealthServiceWatchClient) Conn() (triple_protocol.StreamingClientConn, error) {
	return cli.ServerStreamForClient.Conn()
}

var HealthService_ClientInfo = client.ClientInfo{
	InterfaceName: "health.HealthService",
	MethodNames:   []string{"Check", "Watch"},
	ClientInjectFunc: func(dubboCliRaw interface{}, cli *client.Client) {
		dubboCli := dubboCliRaw.(HealthServiceImpl)
		dubboCli.cli = cli
	},
}

// HealthServiceHandler is an implementation of the health.HealthService service.
type HealthServiceHandler interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Watch(context.Context, *HealthCheckRequest, HealthService_WatchServer) error
}

func RegisterHealthServiceHandler(srv *server.Server, hdlr HealthServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &HealthService_ServiceInfo, opts...)
}

type HealthService_WatchServer interface {
	Send(*HealthCheckResponse) error
	ResponseHeader() http.Header
	ResponseTrailer() http.Header
	Conn() triple_protocol.StreamingHandlerConn
}

type HealthServiceWatchServer struct {
	*triple_protocol.ServerStream
}

func (g *HealthServiceWatchServer) Send(msg *HealthCheckResponse) error {
	return g.ServerStream.Send(msg)
}

var HealthService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "health.HealthService",
	ServiceType:   (*HealthServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "Check",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(HealthCheckRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*HealthCheckRequest)
				res, err := handler.(HealthServiceHandler).Check(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Watch",
			Type: constant.CallServerStream,
			ReqInitFunc: func() interface{} {
				return new(HealthCheckRequest)
			},
			StreamInitFunc: func(baseStream interface{}) interface{} {
				return &HealthServiceWatchServer{baseStream.(*triple_protocol.ServerStream)}
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*HealthCheckRequest)
				stream := args[1].(HealthService_WatchServer)
				if err := handler.(HealthServiceHandler).Watch(ctx, req, stream); err != nil {
					return nil, err
				}
				return nil, nil
			},
		},
	},
}
