application:
  organization : "ikurento.com"
  name  : "BDTService"
  module : "dubbogo user-info client"
  version : "0.0.1"
  owner : "ZX"
  environment : "test"

registries :
  "consul":
    protocol: "consul"
    timeout	: "3s"
    address: "127.0.0.1:8500"
    username: ""
    password: ""

references:
  "DubboService":
    protocol : "dubbo"
    interface : "dubbo.DubboService"
    cluster: "failover"
    methods :
      - name: "SayHello"
        retries: "3"

protocol_conf:
  dubbo:
    reconnect_interval: 0
    connection_number: 2
    heartbeat_period: "5s"
    session_timeout: "20s"
    fail_fast_timeout: "5s"
    pool_size: 64
    pool_ttl: 600
    getty_session_param:
      compress_encoding: false
      tcp_no_delay: true
      tcp_keep_alive: true
      keep_alive_period: "120s"
      tcp_r_buf_size: 262144
      tcp_w_buf_size: 65536
      pkg_rq_size: 1024
      pkg_wq_size: 512
      tcp_read_timeout: "1s"
      tcp_write_timeout: "5s"
      wait_timeout: "1s"
      max_msg_len: 10240
      session_name: "client"

check: true
request_timeout : "3s"
connect_timeout : "3s"
