# dubbo client toml configure file

# pprof
Pprof_Enabled           = true
Pprof_Port              = 10086

# client
Request_Timeout         = "3500ms"
NET_IO_Timeout          = "2s"
Retries                 = 1
# connect timeout
Connect_Timeout         = "100ms"
Selector                = "cache"
Selector_TTL            = "10m"
Registry                = "zookeeper"

# application config
[Application_Config]
Organization            = "ikurento.com"
Name                    = "Pusher"
Module                  = "dubbogo user-info client"
Version                 = "0.0.1"
Owner                   = "ZX"

[Registry_Config]
   # You can indent as you please. Tabs or spaces. TOML don't care.
    Address				= ["127.0.0.1:2181"]
    Timeout				= 3

[[Service_List]]
    Protocol            = "jsonrpc"
    Service             = "com.ikurento.user.UserProvider"
