# dubbo server yaml configure file

# pprof
pprof_enabled : true
pprof_port : 20080

# server
transport : "http"
net_timeout : "3s"

path: ""
# application config
application_config:
    organization : "ikurento.com"
    name : "BDTService"
    module : "dubbogo user-info server"
    version : "0.0.1"
    owner : "ZX"
    environment : "dev"

registries :
    - id: "hangzhouzk"
      type: "zookeeper"
      timeout	: "3s"
      address: "127.0.0.1:2181"
      username: ""
      password: ""

    - id: "shanghaizk"
      type: "zookeeper"
      timeout	: "3s"
      address: "127.0.0.1:2181"
      username: ""
      password: ""


services:
      - registries:
          - "hangzhouzk"
          - "shanghaizk"
        protocol : "dubbo,jsonrpc"
        # 相当于dubbo.xml中的interface
        interface : "com.ikurento.user.UserProvider"
        loadbalance: "random"
        warmup: "100"
        cluster: "failover"
        methods:
            - name: "GetUser"
              retries: 1
              loadbalance: "random"

protocols:
    -   name: "dubbo"
        ip : "192.168.56.1"
        port : 20000
    -   name: "jsonrpc"
        ip: "127.0.0.1"
        port: 20001

