// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: reflection.proto
package triple_reflection

import (
	"context"
	"net/http"
)

import (
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// ServerReflectionName is the fully-qualified name of the ServerReflection service.
	ServerReflectionName = "rpc.reflection.v1alpha.ServerReflection"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServerReflectionServerReflectionInfoProcedure is the fully-qualified name of the ServerReflection's ServerReflectionInfo RPC.
	ServerReflectionServerReflectionInfoProcedure = "/rpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"
)

var (
	_ ServerReflection = (*ServerReflectionImpl)(nil)

	_ ServerReflection_ServerReflectionInfoClient = (*ServerReflectionServerReflectionInfoClient)(nil)

	_ ServerReflection_ServerReflectionInfoServer = (*ServerReflectionServerReflectionInfoServer)(nil)
)

// ServerReflection is a client for the rpc.reflection.v1alpha.ServerReflection service.
type ServerReflection interface {
	ServerReflectionInfo(ctx context.Context, opts ...client.CallOption) (ServerReflection_ServerReflectionInfoClient, error)
}

// NewServerReflection constructs a client for the rpc.reflection.v1alpha.ServerReflection service.
func NewServerReflection(cli *client.Client, opts ...client.ReferenceOption) (ServerReflection, error) {
	group, version, err := cli.Init(&ServerReflection_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &ServerReflectionImpl{
		cli:     cli,
		group:   group,
		version: version,
	}, nil
}

// ServerReflectionImpl implements ServerReflection.
type ServerReflectionImpl struct {
	cli     *client.Client
	group   string
	version string
}

func (c *ServerReflectionImpl) ServerReflectionInfo(ctx context.Context, opts ...client.CallOption) (ServerReflection_ServerReflectionInfoClient, error) {
	opts = appendGroupVersion(opts, c)
	stream, err := c.cli.CallBidiStream(ctx, "rpc.reflection.v1alpha.ServerReflection", "ServerReflectionInfo", opts...)
	if err != nil {
		return nil, err
	}
	rawStream := stream.(*triple_protocol.BidiStreamForClient)
	return &ServerReflectionServerReflectionInfoClient{rawStream}, nil
}

func appendGroupVersion(opts []client.CallOption, c *ServerReflectionImpl) []client.CallOption {
	opts = append(opts, client.WithCallGroup(c.group))
	opts = append(opts, client.WithCallVersion(c.version))
	return opts
}

type ServerReflection_ServerReflectionInfoClient interface {
	Spec() triple_protocol.Spec
	Peer() triple_protocol.Peer
	Send(*ServerReflectionRequest) error
	RequestHeader() http.Header
	CloseRequest() error
	Recv() (*ServerReflectionResponse, error)
	ResponseHeader() http.Header
	ResponseTrailer() http.Header
	CloseResponse() error
}

type ServerReflectionServerReflectionInfoClient struct {
	*triple_protocol.BidiStreamForClient
}

func (cli *ServerReflectionServerReflectionInfoClient) Send(msg *ServerReflectionRequest) error {
	return cli.BidiStreamForClient.Send(msg)
}

func (cli *ServerReflectionServerReflectionInfoClient) Recv() (*ServerReflectionResponse, error) {
	msg := new(ServerReflectionResponse)
	if err := cli.BidiStreamForClient.Receive(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

var ServerReflection_ClientInfo = client.ClientInfo{
	InterfaceName: "rpc.reflection.v1alpha.ServerReflection",
	MethodNames:   []string{"ServerReflectionInfo"},
	ClientInjectFunc: func(dubboCliRaw interface{}, cli *client.Client) {
		dubboCli := dubboCliRaw.(ServerReflectionImpl)
		dubboCli.cli = cli
	},
}

// ServerReflectionHandler is an implementation of the rpc.reflection.v1alpha.ServerReflection service.
type ServerReflectionHandler interface {
	ServerReflectionInfo(context.Context, ServerReflection_ServerReflectionInfoServer) error
}

func RegisterServerReflectionHandler(srv *server.Server, hdlr ServerReflectionHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &ServerReflection_ServiceInfo, opts...)
}

type ServerReflection_ServerReflectionInfoServer interface {
	Send(*ServerReflectionResponse) error
	Recv() (*ServerReflectionRequest, error)
	Spec() triple_protocol.Spec
	Peer() triple_protocol.Peer
	RequestHeader() http.Header
	ResponseHeader() http.Header
	ResponseTrailer() http.Header
	Conn() triple_protocol.StreamingHandlerConn
}

type ServerReflectionServerReflectionInfoServer struct {
	*triple_protocol.BidiStream
}

func (srv *ServerReflectionServerReflectionInfoServer) Send(msg *ServerReflectionResponse) error {
	return srv.BidiStream.Send(msg)
}

func (srv ServerReflectionServerReflectionInfoServer) Recv() (*ServerReflectionRequest, error) {
	msg := new(ServerReflectionRequest)
	if err := srv.BidiStream.Receive(msg); err != nil {
		return nil, err
	}
	return msg, nil
}

var ServerReflection_ServiceInfo = server.ServiceInfo{
	InterfaceName: "rpc.reflection.v1alpha.ServerReflection",
	ServiceType:   (*ServerReflectionHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "ServerReflectionInfo",
			Type: constant.CallBidiStream,
			StreamInitFunc: func(baseStream interface{}) interface{} {
				return &ServerReflectionServerReflectionInfoServer{baseStream.(*triple_protocol.BidiStream)}
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				stream := args[0].(ServerReflection_ServerReflectionInfoServer)
				if err := handler.(ServerReflectionHandler).ServerReflectionInfo(ctx, stream); err != nil {
					return nil, err
				}
				return nil, nil
			},
		},
	},
}
