name: CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: "*"

jobs:

  build:
    name: ubuntu-latest ${{ matrix.config.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - go_version: 1.13
    steps:


    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.config.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: License Check
      run: |
        go fmt ./... && [[ -z `git status -s` ]]
        sh before_validate_license.sh
        chmod u+x /tmp/tools/license/license-header-checker
        /tmp/tools/license/license-header-checker -v -a -r -i vendor  /tmp/tools/license/license.txt . go  && [[ -z `git status -s` ]]

    - name: Test
      run: |
        chmod u+x before_ut.sh && ./before_ut.sh
        go mod vendor && go test ./... -coverprofile=coverage.txt -covermode=atomic
        chmod +x integrate_test.sh && ./integrate_test.sh

    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)
      
    - name: DingTalk Message Notify
      # You may pin to the exact commit or the version.
      # uses: zcong1993/actions-ding@2a68a4d06ed966d2e5c28178e7187c107ec57862
      uses: zcong1993/actions-ding@v3.0.1
      # if: ${{ github.repository == 'apache/dubbo-go' }}
      with:
        # DingDing bot token
        dingToken: 6374f1bf8d4f23cde81d4a4b8c1f0bc98cc92b5151ca938ab938d3d7f4230fc4
        secret: SECa98677289194bb0e5caec3051301d06515750ff1bd2f932a4704298afb2e0ae6
        # Post Body to send
        body: |
          {
            "msgtype": "markdown",
            "markdown": {
                "title": "Github Actions",
                "text": "## Github Actions \n - name: CI \n - repository: ${{ github.repository }} \n - trigger: ${{ github.actor }} \n - event: ${{ github.event_name }} \n - ref: ${{ github.ref }} \n - status: [${{ job.status	}}](https://github.com/sdttttt/dubbo-go/actions/runs/${{ github.run_id }}) \n - environment: ${{ runner.os }} \n - SHA: ${{ github.sha }}"
            }
          }
