/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

import (
	resource "dubbo.apache.org/dubbo-go/v3/xds/client/resource"
)

// EWatcher is an autogenerated mock type for the EWatcher type
type EWatcher struct {
	mock.Mock
}

// Destroy provides a mock function with given fields:
func (_m *EWatcher) Destroy() {
	_m.Called()
}

// Handle provides a mock function with given fields: update, err
func (_m *EWatcher) Handle(update resource.EndpointsUpdate, err error) {
	_m.Called(update, err)
}

// SetCancelFunction provides a mock function with given fields: cancel
func (_m *EWatcher) SetCancelFunction(cancel func()) {
	_m.Called(cancel)
}
